// имена type для actions

const STORE_TYPE = "app";

export const CHECK_IS_LOGIN = `${STORE_TYPE}/CHECK_IS_LOGIN`;
export const LOG_IN = `${STORE_TYPE}/LOG_IN`;
export const LOG_IN_SUCCESS = `${STORE_TYPE}/LOG_IN_SUCCESS`;
export const LOG_IN_FAILURE = `${STORE_TYPE}/LOG_IN_FAILURE`;
export const SIGN_UP = `${STORE_TYPE}/SIGN_UP`;
export const SIGN_UP_SUCCESS = `${STORE_TYPE}/SIGN_UP_SUCCESS`;
export const SIGN_UP_FAILURE = `${STORE_TYPE}/SIGN_UP_FAILURE`;
export const LOG_OUT = `${STORE_TYPE}/LOG_OUT`;


export const GET_CARD = `${STORE_TYPE}/GET_CARD`;
export const GET_CARD_SUCCESS = `${STORE_TYPE}/GET_CARD_SUCCESS`;
export const GET_CARD_FAILURE = `${STORE_TYPE}/GET_CARD_FAILURE`;
export const SEND_CARD = `${STORE_TYPE}/SEND_CARD`;
export const SEND_CARD_SUCCESS = `${STORE_TYPE}/SEND_CARD_SUCCESS`;
export const SEND_CARD_FAILURE = `${STORE_TYPE}/SEND_CARD_FAILURE`;

export const GET_ADDRESS = `${STORE_TYPE}/GET_ADDRESS`;
export const GET_ADDRESS_SUCCESS = `${STORE_TYPE}/GET_ADDRESS_SUCCESS`;
export const GET_ADDRESS_FAILURE = `${STORE_TYPE}/GET_ADDRESS_FAILURE`;

export const ROUTE_DELETE = `${STORE_TYPE}/ROUTE_DELETE`;
export const ROUTE = `${STORE_TYPE}/ROUTE`;
export const ROUTE_SUCCESS = `${STORE_TYPE}/ROUTE_SUCCESS`;
export const ROUTE_FAILURE = `${STORE_TYPE}/ROUTE_FAILURE`;
